// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call2_action: dynamic(() => import("./Call2Action")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  photo_grid: dynamic(() => import("./PhotoGrid")),
  project_grid: dynamic(() => import("./ProjectGrid")),
  quote: dynamic(() => import("./Quote")),
  text: dynamic(() => import("./Text")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  video: dynamic(() => import("./Video")),
};
